# sampler selection
use_ddim: true # false --> DDPM; true --> DDIM
eta: 0.0 # DDIM noise control; 0 is totally deterministic.
# scheduler/model
clip_sample: true
clip_sample_range: 1.0

run_name: ddpm
seed: 42
data_dir: ./data
image_size: 128
batch_size: 640
num_workers: 8
num_classes: #NUM_CLASSES
num_epochs: 50
learning_rate: 1e-3
weight_decay: 0.1
num_train_timesteps: #train timesteps
num_inference_steps: 50
beta_start: #BETA START
beta_end: #BETA END
beta_schedule: #BETA SCHEDULE

variance_type: fixed_small
predictor_type: epsilon
unet_in_size: 128
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.0